[package]
name = "flp"
version = "0.4.2"
edition = "2024"

[dependencies]
common = {path = "../common"}
serde_json = {workspace = true}
serde = {workspace = true, features = ["derive"]}
anyhow = {workspace = true}
csv = {workspace = true}
