[package]
name = "common"
version = "0.2.0"
edition = "2024"

[dependencies]
ureq = {workspace = true}
anyhow = {workspace = true}
serde_json = {workspace = true}
serde = {workspace = true, features = ["derive"]}
dotenvy = {workspace = true}